[package]
name = "matrix_display"
description = "A library to display a matrix in command line with pretty unicode separators"
version = "0.5.0"
authors = ["Pierre Chevalier <pierrechevalier83@gmail.com>"]
license = "MIT"

[dependencies]
ansi_term= "0.9"
unicode-width= "0.1.4"
